### ISSUE TITLE
add a SSG

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/ssg-dataset#4]
```
rstudio/bookdown:
  lang: R
segmentio/metalsmith:
  lang: js
middleman/middleman:
  lang: ruby
getgridea/gridea    
  lang: js
jnordberg/wintersmith
  lang: js
lektor/lektor  
  lang: python
JohnSundell/Publish  
  lang: swift
```
